Fix PluginException in StackTaskConfigurationType
com.intellij.diagnostic.PluginException: The default implementation of method 'getId' is deprecated, you need to override it in 'class com.haskforce.run.stack.task.StackTaskConfigurationType$$anon$1'. The default implementation delegates to 'getName' which may be localized, but return value of this method must not depend on current localization. [Plugin: com.haskforce]